version: "3" 
services:
    web:    
        image: lfmingo/lfmingo:1.0
        deploy:
            replicas: 5 
            resources:
                limits:
                    cpus: "0.1" 
                    memory: 50M
            restart_policy: 
                condition: on-failure
        ports:
            - "8080:80"
        networks: 
            - webnet
        
    visualizer:
        image: dockersamples/visualizer:stable 
        ports:
            - "8090:8080" 
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock" 
        deploy:
            placement:
                constraints: [node.role == manager]
        networks: 
            - webnet

    redis:
        image: redis:latest
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
            - webnet 
        volumes:
            - redis-data:/data 

networks:
    webnet: 
volumes:
    redis-data: